package Vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.text.Caret;

/**
 *
 * @author Alberto Fernández Merchán & Juan Manuel Ruíz Pérez
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Dimension dPantalla = Toolkit.getDefaultToolkit().getScreenSize();
    public Lienzo lienzo;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {

        initComponents();
        lienzo = new Lienzo(this);
        lienzo.setBounds(0,
                (int) 12,
                (int) (dPantalla.getWidth() - jPanel2.getWidth() - 10),
                (int) (dPantalla.getHeight()));
        add(lienzo);
        lienzo.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        lienzo.setVisible(true);
        
        jPanel2.setBounds((int) (lienzo.getWidth()), 0, (int)(dPantalla.getWidth() - lienzo.getWidth()), (int)dPantalla.getHeight());
        jPanel2.setPreferredSize(new java.awt.Dimension((int)dPantalla.getWidth(), (int)dPantalla.getHeight()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        Cargar = new javax.swing.JButton();
        GenerarFichero = new javax.swing.JButton();
        GenerarGrafico = new javax.swing.JButton();
        cadena = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        EstadoCadena = new javax.swing.JLabel();
        reconocerCadena = new javax.swing.JButton();
        PasoAPaso = new javax.swing.JButton();
        pasoAnterior = new javax.swing.JButton();
        BotonCrearAutomata = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 32767));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        GuardarComoEditor = new javax.swing.JMenuItem();
        GuardarEditor = new javax.swing.JMenuItem();
        CargarEditor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ayudaMenu = new javax.swing.JMenuItem();
        creditosMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[AMC] Práctica 2 - Alberto Fernández Merchán y Juan Manuel Ruíz Pérez");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel2.setBackground(Color.decode("#669999"));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Panel de Edición", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension((int)dPantalla.getWidth(), (int)dPantalla.getHeight()));

        TextoArea.setBackground(Color.decode("#466767"));
        TextoArea.setColumns(20);
        TextoArea.setFont(new java.awt.Font("MS Gothic", 2, 14)); // NOI18N
        TextoArea.setForeground(new java.awt.Color(255, 255, 255));
        TextoArea.setLineWrap(true);
        TextoArea.setRows(5);
        TextoArea.setWrapStyleWord(true);
        TextoArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edición de Texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        TextoArea.setPreferredSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(TextoArea);

        jPanel3.setBackground(Color.decode("#466767"));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        Cargar.setText("Cargar Fichero");
        Cargar.setActionCommand("Cargar");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        jPanel3.add(Cargar);

        GenerarFichero.setText("Guardar Fichero");
        GenerarFichero.setActionCommand("Guardar");
        jPanel3.add(GenerarFichero);

        GenerarGrafico.setText("Generar Grafo");
        GenerarGrafico.setActionCommand("Generar");
        jPanel3.add(GenerarGrafico);

        cadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadenaActionPerformed(evt);
            }
        });

        jLabel1.setText("Reconocer Cadena");

        EstadoCadena.setText("RECHAZADA");

        reconocerCadena.setText("Reconocer Cadena");
        reconocerCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconocerCadenaActionPerformed(evt);
            }
        });

        PasoAPaso.setText("Siguiente Paso");
        PasoAPaso.setActionCommand("PasoAPaso");

        pasoAnterior.setText("Paso Anterior");

        BotonCrearAutomata.setText("Crear autómata");
        BotonCrearAutomata.setActionCommand("CrearAutómata");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reconocerCadena)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cadena))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EstadoCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BotonCrearAutomata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pasoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasoAPaso, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EstadoCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reconocerCadena)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasoAPaso)
                    .addComponent(pasoAnterior)
                    .addComponent(BotonCrearAutomata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Archivo");

        GuardarComoEditor.setText("Guardar Como...");
        GuardarComoEditor.setActionCommand("GuardarComo");
        jMenu1.add(GuardarComoEditor);

        GuardarEditor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        GuardarEditor.setText("Guardar");
        jMenu1.add(GuardarEditor);

        CargarEditor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CargarEditor.setText("Cargar Fichero");
        CargarEditor.setActionCommand("Cargar");
        CargarEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarEditorActionPerformed(evt);
            }
        });
        jMenu1.add(CargarEditor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        ayudaMenu.setText("Cómo usar el programa");
        ayudaMenu.setActionCommand("ayuda");
        ayudaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaMenuActionPerformed(evt);
            }
        });
        jMenu2.add(ayudaMenu);

        creditosMenu.setText("Créditos...");
        creditosMenu.setActionCommand("creditos");
        jMenu2.add(creditosMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CargarEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarEditorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarEditorActionPerformed

    private void ayudaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaMenuActionPerformed

    private void reconocerCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconocerCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reconocerCadenaActionPerformed

    private void cadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadenaActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonCrearAutomata;
    public javax.swing.JButton Cargar;
    public javax.swing.JMenuItem CargarEditor;
    public javax.swing.JLabel EstadoCadena;
    public javax.swing.JButton GenerarFichero;
    public javax.swing.JButton GenerarGrafico;
    public javax.swing.JMenuItem GuardarComoEditor;
    public javax.swing.JMenuItem GuardarEditor;
    public javax.swing.JButton PasoAPaso;
    public javax.swing.JTextArea TextoArea;
    public javax.swing.JMenuItem ayudaMenu;
    public javax.swing.JTextField cadena;
    public javax.swing.JMenuItem creditosMenu;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton pasoAnterior;
    public javax.swing.JButton reconocerCadena;
    // End of variables declaration//GEN-END:variables
}
