package Vista;

import javax.swing.ImageIcon;
import javax.swing.JTable;

/**
 *
 * @author Alberto Fernández
 */
public class LongitudAristas extends javax.swing.JFrame {

    /**
     * Creates new form SolucionDetallada
     */
    public LongitudAristas() {
        this.setIconImage(new ImageIcon(getClass().getResource("caminos.png")).getImage());
        initComponents();
    }
    
    public JTable getTabla(){
        return TablaAristas;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAristas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabla de Pesos");

        TablaAristas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablaAristas.setForeground(new java.awt.Color(0, 0, 0));
        TablaAristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaAristas.setOpaque(false);
        TablaAristas.setRequestFocusEnabled(false);
        TablaAristas.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        TablaAristas.setShowGrid(true);
        TablaAristas.getTableHeader().setReorderingAllowed(false);
        TablaAristas.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(TablaAristas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaAristas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
