package Vista;

import Controlador.Controlador;
import Modelo.Algoritmos;
import Modelo.Punto;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Alberto Fernández
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private DecimalFormat df = new DecimalFormat("####0.00");
    private Controlador c;
    private Algoritmos a;
    private InformacionAvanzada ia;
    private AutoAyuda ayuda;
    private Mensaje m;
    private Aleatorio vAleatorio;
    private ArrayList<Punto> PuntosFichero;
    private int puntoOrigen;

    final String COLORAQUA = "#058D9B";

    public VentanaPrincipal(Controlador c, InformacionAvanzada ia) {
        m = new Mensaje();
        ayuda = new AutoAyuda();
        vAleatorio = new Aleatorio();
        this.c = c;
        this.ia = ia;
        this.a = new Algoritmos(this, this.c.getvAleatorio(), this.c.getInformacionAvanzada(), this.c.getvMensaje());
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("Icono.png")).getImage());
        canvas1.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        a.setCanvas(canvas1);

    }

    public void setPuntoOrigen(int id) {
        puntoOrigen = id;
    }

    public Canvas getCanvas() {
        return this.canvas1;
    }

    public Algoritmos getAlgoritmo() {
        return this.a;
    }

    public void escribirEtiquetasSuma(Integer[] L) {
        int suma = 0;
        for (int i = 0; i < L.length; i++) {
            suma += L[i];
        }
        this.EtiquetaSumaDistancias.setText("" + suma);
    }

    public void escribirEtiquetasSolucion(Integer[] L) {
        if (L.length < 60) {
            String solucion = "{  ";
            for (int i = 0; i < L.length - 1; i++) {
                if (i != puntoOrigen) {
                    solucion += (Integer.toString(L[i]) + "  ");
                }
            }
            if (L.length - 1 != puntoOrigen) {
                solucion += ("" + Integer.toString(L[L.length - 1]) + " ");
            }
                solucion += "}";
            VectorDistanciasMinimas.setText(solucion);
        } else {
            VectorDistanciasMinimas.setText("Solo se muestra para vectores menores de 60.");
        }
    }

    public void escribirInformacionAvanzada(String tipoAlgoritmo, long TiempoFin, int repeticiones) {
        this.BotonInformacionAvanzada.setEnabled(true);
        ia.NombreAlgoritmo.setText(tipoAlgoritmo);
        ia.repeticiones.setText(Integer.toString(repeticiones));

        if (TiempoFin > 1e9) {
            ia.TiempoEjec.setText("" + (TiempoFin) / 1e9 + " s");
        } else if (TiempoFin > 1e6) {
            ia.TiempoEjec.setText("" + (TiempoFin) / 1e6 + " ms");
        } else {
            ia.TiempoEjec.setText("" + (TiempoFin) + " ns");
        }
    }

    public void escribirEtiquetaPuntos(ArrayList<Punto> puntosSolucion) {

        if (puntosSolucion.size() < 10) {
            String solucion = "";

            for (int i = 0; i < puntosSolucion.size() - 1; i++) {
                solucion += "" + puntosSolucion.get(i).getId() + " , ";
            }

            solucion += "" + puntosSolucion.get(puntosSolucion.size() - 1).getId();

            EtiquetaPuntosSolucion.setText(solucion);
        } else {
            EtiquetaPuntosSolucion.setText("Solo se muestra para menos de 10 puntos...");
        }
    }

    private static int contarCifras(int a) {
        int tmp = a;
        int numCifras = 0;
        while (tmp > 0) {
            tmp = tmp / 10;
            numCifras++;
        }
        return numCifras;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        canvas1 = new CanvasPuntos(a);
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EtiquetaSumaDistancias = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Fichero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        VectorDistanciasMinimas = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EtiquetaPuntosSolucion = new javax.swing.JLabel();
        BotonAleatorio = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        BotonBuscar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        Algoritmo = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        BotonInformacionAvanzada = new javax.swing.JButton();
        esExperimental = new javax.swing.JCheckBox();
        Repeticiones = new javax.swing.JTextField();
        PuntoOrigen = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        FicheroMenuTab = new javax.swing.JMenu();
        GuardarFichero = new javax.swing.JMenuItem();
        CargarFichero = new javax.swing.JMenuItem();
        FicheroAleatorio = new javax.swing.JMenuItem();
        AyudaMenuTab = new javax.swing.JMenu();
        AyudaBoton = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuVista = new javax.swing.JMenu();
        BotonModoOscuro = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        TablaPesos = new javax.swing.JMenuItem();
        TablaEvolucion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Práctica 1b - AMC - Alberto Fernández Merchán");
        setExtendedState(6);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setName("Ventana"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        //canvas1 = new CanvasPuntos();
        canvas1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(106, 1, 1));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fichero Seleccionado");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Suma Total:");

        EtiquetaSumaDistancias.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaSumaDistancias.setText("0");

        Fichero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Fichero.setForeground(new java.awt.Color(255, 255, 255));
        Fichero.setText("---");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Longitudes Mínimas");

        VectorDistanciasMinimas.setForeground(new java.awt.Color(255, 255, 255));
        VectorDistanciasMinimas.setText("{---}");

        jPanel7.setBackground(new java.awt.Color(106, 1, 1));
        jPanel7.setForeground(Color.decode(COLORAQUA));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Genera un fichero .tsp aleatorio");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puntos Solucion: ");

        EtiquetaPuntosSolucion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EtiquetaPuntosSolucion.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaPuntosSolucion.setText("{---}");

        BotonAleatorio.setText("Aleatorio");
        BotonAleatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EtiquetaSumaDistancias))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VectorDistanciasMinimas))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EtiquetaPuntosSolucion)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Fichero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAleatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(EtiquetaSumaDistancias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EtiquetaPuntosSolucion)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(VectorDistanciasMinimas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Fichero))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonAleatorio)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(106, 1, 1));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        BotonBuscar.setText("Buscar");
        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BotonSalir.setText("Salir");
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        Algoritmo.setSelectedItem("Dijkstra");
        Algoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Dijkstra"}));
        Algoritmo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Algoritmo.setName(""); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Elige el algoritmo:");

        BotonInformacionAvanzada.setText("Información Avanzada");
        BotonInformacionAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInformacionAvanzadaActionPerformed(evt);
            }
        });

        esExperimental.setBackground(new java.awt.Color(106, 1, 1));
        esExperimental.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        esExperimental.setForeground(new java.awt.Color(255, 255, 255));
        esExperimental.setText("Estudio Experimental");
        esExperimental.setToolTipText("Selecciona para repetir la búsqueda.");
        esExperimental.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Repeticiones.setBackground(new java.awt.Color(106, 1, 1));
        Repeticiones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Repeticiones.setForeground(new java.awt.Color(255, 255, 255));
        Repeticiones.setText("10");
        Repeticiones.setToolTipText("Número de veces que se repetirá la búsqueda.");
        Repeticiones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repeticiones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        Repeticiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeticionesActionPerformed(evt);
            }
        });
        Repeticiones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RepeticionesKeyTyped(evt);
            }
        });

        PuntoOrigen.setBackground(new java.awt.Color(106, 1, 1));
        PuntoOrigen.setForeground(new java.awt.Color(255, 255, 255));
        PuntoOrigen.setText("0");
        PuntoOrigen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id. Punto Origen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PuntoOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PuntoOrigenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Algoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(esExperimental)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonInformacionAvanzada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(BotonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PuntoOrigen)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PuntoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonBuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonInformacionAvanzada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonSalir))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Algoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(esExperimental))))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        jPanel1.getAccessibleContext().setAccessibleName("Información");

        FicheroMenuTab.setText("Fichero");

        GuardarFichero.setBounds(10,10,20,20);
        ImageIcon imagen2 = new ImageIcon("src\\Vista\\save.png");
        Image img2 = imagen2.getImage();
        Image newimg2 = img2.getScaledInstance(GuardarFichero.getWidth(), GuardarFichero.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icono2 = new ImageIcon(newimg2);
        GuardarFichero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        GuardarFichero.setIcon(icono2);
        GuardarFichero.setText("Guardar Fichero...");
        GuardarFichero.setActionCommand("Guardar");
        GuardarFichero.setOpaque(false);
        GuardarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarFicheroActionPerformed(evt);
            }
        });
        FicheroMenuTab.add(GuardarFichero);

        CargarFichero.setBounds(10,10,20,20);
        ImageIcon imagen3 = new ImageIcon("src\\Vista\\cargar.png");
        Image img3 = imagen3.getImage();
        Image newimg3 = img3.getScaledInstance(CargarFichero.getWidth(), CargarFichero.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icono3 = new ImageIcon(newimg3);
        CargarFichero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CargarFichero.setIcon(icono3);
        CargarFichero.setText("Cargar Fichero");
        CargarFichero.setActionCommand("ElegirFichero");
        CargarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarFicheroActionPerformed(evt);
            }
        });
        FicheroMenuTab.add(CargarFichero);

        FicheroAleatorio.setBounds(10,10,20,20);
        ImageIcon imagen4 = new ImageIcon("src\\Vista\\aleatorio.png");
        Image img4 = imagen4.getImage();
        Image newimg4 = img4.getScaledInstance(GuardarFichero.getWidth(), GuardarFichero.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icono4 = new ImageIcon(newimg4);
        FicheroAleatorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        FicheroAleatorio.setIcon(icono4);
        FicheroAleatorio.setText("Generar Fichero Aleatorio");
        FicheroAleatorio.setActionCommand("Aleatorio");
        FicheroAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FicheroAleatorioActionPerformed(evt);
            }
        });
        FicheroMenuTab.add(FicheroAleatorio);

        jMenuBar1.add(FicheroMenuTab);

        AyudaMenuTab.setText("Ayuda");

        GuardarFichero.setBounds(10,10,20,20);
        ImageIcon imagen = new ImageIcon("src\\Vista\\ayuda.png");
        Image img = imagen.getImage();
        Image newimg = img.getScaledInstance(GuardarFichero.getWidth(), GuardarFichero.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icono = new ImageIcon(newimg);
        AyudaBoton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        AyudaBoton.setIcon(icono);
        AyudaBoton.setText("Ayuda");
        AyudaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaBotonActionPerformed(evt);
            }
        });
        AyudaMenuTab.add(AyudaBoton);

        jMenuItem1.setText("Créditos...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        AyudaMenuTab.add(jMenuItem1);

        jMenuBar1.add(AyudaMenuTab);

        MenuVista.setText("Vista");

        BotonModoOscuro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        BotonModoOscuro.setSelected(true);
        BotonModoOscuro.setText("Modo Oscuro");
        BotonModoOscuro.setActionCommand("ModoOscuro");
        MenuVista.add(BotonModoOscuro);

        jMenu1.setText("Solucion Detallada");

        TablaPesos.setText("Tabla de Pesos");
        TablaPesos.setActionCommand("Pesos");
        TablaPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablaPesosActionPerformed(evt);
            }
        });
        jMenu1.add(TablaPesos);

        TablaEvolucion.setText("Tabla  de Evolución");
        TablaEvolucion.setActionCommand("Evolucion");
        TablaEvolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablaEvolucionActionPerformed(evt);
            }
        });
        jMenu1.add(TablaEvolucion);

        MenuVista.add(jMenu1);

        jMenuBar1.add(MenuVista);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarFicheroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarFicheroActionPerformed

    private void AyudaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaBotonActionPerformed
        ayuda.setVisible(true);
    }//GEN-LAST:event_AyudaBotonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        m.Message("creditos", "Autor: Alberto Fernández Merchán\n Año: 2021");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void CargarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarFicheroActionPerformed


    }//GEN-LAST:event_CargarFicheroActionPerformed

    private void FicheroAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FicheroAleatorioActionPerformed

    }//GEN-LAST:event_FicheroAleatorioActionPerformed

    private void RepeticionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RepeticionesKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= '0' && key <= '9';

        if (!numeros) {
            evt.consume();
        }

        if (Repeticiones.getText().trim().length() == 3) {
            evt.consume();
        }
    }//GEN-LAST:event_RepeticionesKeyTyped

    private void RepeticionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeticionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepeticionesActionPerformed

    private void BotonInformacionAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInformacionAvanzadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonInformacionAvanzadaActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void PuntoOrigenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PuntoOrigenKeyTyped
               int key = evt.getKeyChar();

        boolean numeros = key >= '0' && key <= '9';

        if (!numeros) {
            evt.consume();
        }

        if (PuntoOrigen.getText().trim().length() >= contarCifras(a.getNumPuntos())) {
            evt.consume();
        }
    }//GEN-LAST:event_PuntoOrigenKeyTyped

    private void TablaPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablaPesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaPesosActionPerformed

    private void TablaEvolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablaEvolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaEvolucionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new VentanaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Algoritmo;
    private javax.swing.JMenuItem AyudaBoton;
    private javax.swing.JMenu AyudaMenuTab;
    public javax.swing.JButton BotonAleatorio;
    public javax.swing.JButton BotonBuscar;
    public javax.swing.JButton BotonInformacionAvanzada;
    public javax.swing.JRadioButtonMenuItem BotonModoOscuro;
    public javax.swing.JButton BotonSalir;
    public javax.swing.JMenuItem CargarFichero;
    public javax.swing.JLabel EtiquetaPuntosSolucion;
    public javax.swing.JLabel EtiquetaSumaDistancias;
    public javax.swing.JLabel Fichero;
    public javax.swing.JMenuItem FicheroAleatorio;
    public javax.swing.JMenu FicheroMenuTab;
    public javax.swing.JMenuItem GuardarFichero;
    private javax.swing.JMenu MenuVista;
    public javax.swing.JTextField PuntoOrigen;
    public javax.swing.JTextField Repeticiones;
    public javax.swing.JMenuItem TablaEvolucion;
    public javax.swing.JMenuItem TablaPesos;
    public javax.swing.JLabel VectorDistanciasMinimas;
    public java.awt.Canvas canvas1;
    public javax.swing.JCheckBox esExperimental;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
